### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by fsssaver** [snssll/poe2openai#1]
INFO:     Started server process [9080]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8765 (Press CTRL+C to quit)
INFO:     192.168.2.100:4620 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found
INFO:     192.168.2.100:4656 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found
INFO:     192.168.2.100:4656 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found
INFO:     192.168.2.100:4656 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found
INFO:     192.168.2.100:4656 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found
INFO:     192.168.2.100:4724 - "POST /v1/v1/chat/completions HTTP/1.1" 404 Not Found
INFO:     192.168.2.100:4724 - "POST /v1/v1/chat/completions HTTP/1.1" 404 Not Found
INFO:     192.168.2.100:4724 - "POST /v1/v1/chat/completions HTTP/1.1" 404 Not Found
INFO:     192.168.2.100:4724 - "POST /v1/v1/chat/completions HTTP/1.1" 404 Not Found

**Comment by snssll** [comment]
Our service only responds to @app.post("/openai/chat/completions"). You can try modifying the code on line 51 or changing the request URL to match this endpoint.
